from .elements import *
from .petri_net import *

class PlainNet(ColoredPetriNet):
    def __init__(self, name):
        super().__init__(name)

class TestNet(ColoredPetriNet):
    def __init__(self, name):
        super().__init__(name)
        self.p1 = Place('p1', {'0': 25})
        self.p2 = Place('p2', {'0': 0})
        self.p3 = Place('p3', {'0': 0})
        self.t1 = Transition('t1')
        self.t2 = Transition('t2')
        self.add_node(self.t1)
        self.add_node(self.t2)
        self.add_node(self.p1)
        self.add_node(self.p2)
        self.add_node(self.p3)
        self.add_arc(self.p1, self.t1)
        self.add_arc(self.t1, self.p2)
        self.add_arc(self.p2, self.t2)
        self.add_arc(self.t2, self.p3)
        
class EmptyNet(ColoredPetriNet):
    def __init__(self, name):
        super().__init__(name)
        
class S3PR_Net(ColoredPetriNet):
    def __init__(self, name):
        super().__init__(name)
        p1 = Place('p1', initial_marking={'0': 10}, capacity=10)
        p2 = Place('p2', initial_marking={'0': 10}, capacity=10)
        p3 = Place('p3', initial_marking={'0': 10}, capacity=10)
        p4 = Place('p4', capacity=10)
        p5 = Place('p5', capacity=10)
        p6 = Place('p6', capacity=10)
        p7 = Place('p7')
        p8 = Place('p8')
        p9 = Place('p9')
        p10 = Place('p10')
        p11 = Place('p11')
        p12 = Place('p12')
        p13 = Place('p13')
        p14 = Place('p14')
        p15 = Place('p15')
        p16 = Place('p16')
        p17 = Place('p17')
        p18 = Place('p18')
        p19 = Place('p19')
        p20 = Place('p20')
        p21 = Place('p21')
        p22 = Place('p22')
        p23 = Place('p23', initial_marking={'0': 1}, place_type='resource')
        p24 = Place('p24', initial_marking={'0': 2}, place_type='resource', capacity=2)
        p25 = Place('p25', initial_marking={'0': 2}, place_type='resource', capacity=2)
        p26 = Place('p26', initial_marking={'0': 1}, place_type='resource')
        p27 = Place('p27', initial_marking={'0': 2}, place_type='resource', capacity=2)
        p28 = Place('p28', initial_marking={'0': 2}, place_type='resource', capacity=2)
        p29 = Place('p29', initial_marking={'0': 1}, place_type='resource')
        
        t0 = Transition('t0')
        t1 = Transition('t1')
        t2 = Transition('t2')
        t3 = Transition('t3', action_bonus=100)
        t4 = Transition('t4')
        t5 = Transition('t5')
        t6 = Transition('t6')
        t7 = Transition('t7')
        t8 = Transition('t8')
        t9 = Transition('t9')
        t10 = Transition('t10')
        t11 = Transition('t11')
        t12 = Transition('t12')
        t13 = Transition('t13', action_bonus=100)
        t14 = Transition('t14')
        t15 = Transition('t15')
        t16 = Transition('t16')
        t17 = Transition('t17')
        t18 = Transition('t18')
        t19 = Transition('t19', action_bonus=100)
        
        self.add_node(p1)
        self.add_node(p2)
        self.add_node(p3)
        self.add_node(p4)
        self.add_node(p5)
        self.add_node(p6)
        self.add_node(p7)
        self.add_node(p8)
        self.add_node(p9)
        self.add_node(p10)
        self.add_node(p11)
        self.add_node(p12)
        self.add_node(p13)
        self.add_node(p14)
        self.add_node(p15)
        self.add_node(p16)
        self.add_node(p17)
        self.add_node(p18)
        self.add_node(p19)
        self.add_node(p20)
        self.add_node(p21)
        self.add_node(p22)
        self.add_node(p23)
        self.add_node(p24)
        self.add_node(p25)
        self.add_node(p26)
        self.add_node(p27)
        self.add_node(p28)
        self.add_node(p29)
        
        self.add_node(t0)
        self.add_node(t1)
        self.add_node(t2)
        self.add_node(t3)
        self.add_node(t4)
        self.add_node(t5)
        self.add_node(t6)
        self.add_node(t7)
        self.add_node(t8)
        self.add_node(t9)
        self.add_node(t10)
        self.add_node(t11)
        self.add_node(t12)
        self.add_node(t13)
        self.add_node(t14)
        self.add_node(t15)
        self.add_node(t16)
        self.add_node(t17)
        self.add_node(t18)
        self.add_node(t19)
        
        self.add_arc(p1, t0)
        self.add_arc(p23, t0)
        self.add_arc(t0, p7)
        self.add_arc(p7, t1)
        self.add_arc(p25, t1)
        self.add_arc(t1, p8)
        self.add_arc(t1, p23)
        self.add_arc(p8, t2)
        self.add_arc(p23, t2)
        self.add_arc(t2, p9)
        self.add_arc(t2, p25)
        self.add_arc(p9, t3)
        self.add_arc(t3, p23)
        self.add_arc(t3, p4)
        self.add_arc(p2, t4)
        self.add_arc(p29, t4)
        self.add_arc(t4, p10)
        self.add_arc(p10, t5)
        self.add_arc(p24, t5)
        self.add_arc(t5, p11)
        self.add_arc(t5, p29)
        self.add_arc(p10, t6)
        self.add_arc(p28, t6)
        self.add_arc(t6, p12)
        self.add_arc(t6, p29)
        self.add_arc(p11, t7)
        self.add_arc(p23, t7)
        self.add_arc(t7, p13)
        self.add_arc(t7, p24)
        self.add_arc(p12, t8)
        self.add_arc(p23, t8)
        self.add_arc(t8, p14)
        self.add_arc(t8, p28)
        self.add_arc(p13, t9)
        self.add_arc(p25, t9)
        self.add_arc(t9, p23)
        self.add_arc(t9, p15)
        self.add_arc(p14, t10)
        self.add_arc(p27, t10)
        self.add_arc(t10, p23)
        self.add_arc(t10, p16)
        self.add_arc(p15, t11)
        self.add_arc(p26, t11)
        self.add_arc(t11, p25)
        self.add_arc(t11, p17)
        self.add_arc(p16, t12)
        self.add_arc(p26, t12)
        self.add_arc(t12, p27)
        self.add_arc(t12, p17)
        self.add_arc(p17, t13)
        self.add_arc(t13, p5)
        self.add_arc(t13, p26)
        self.add_arc(p3, t14)
        self.add_arc(p26, t14)
        self.add_arc(t14, p18)
        self.add_arc(p18, t15)
        self.add_arc(p27, t15)
        self.add_arc(t15, p26)
        self.add_arc(t15, p19)
        self.add_arc(p19, t16)
        self.add_arc(p23, t16)
        self.add_arc(t16, p27)
        self.add_arc(t16, p20)
        self.add_arc(p20, t17)
        self.add_arc(p28, t17)
        self.add_arc(t17, p23)
        self.add_arc(t17, p21)
        self.add_arc(p21, t18)
        self.add_arc(p29, t18)
        self.add_arc(t18, p22)
        self.add_arc(t18, p28)
        self.add_arc(p22, t19)
        self.add_arc(t19, p29)
        self.add_arc(t19, p6)